project:
  name: "Reposeed Server"
  oneLiner: "Hosted version for [Reposeed](https://github.com/okkur/reposeed) repository base file generation"
  state: "unstable"
  image: "https://github.com/okkur/reposeed/blob/master/media/logo.svg"
  website: ""
  description: |
    Hosted version to simplify usage of Reposeed from a web interface.
  version: "v0.1.0"

vision:
  type: "community"
  overview: |
    Providing a hosted version for [Reposeed](https://github.com/okkur/reposeed).


contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/reposeed-server/labels/starter%20issue"

supportLinks:
  documentation: "/docs"

readme:
  usageExample: |
    ```
    go get -v -u github.com/okkur/reposeed-server
    ```

    After installation create an .env file
    ```
    echo 'PORT=":8080"' >> .env
    echo 'STORAGE="./storage/zips/"' >> .env # Path to your storage folder for zip files
    ```

    To start the server run ```reposeed-server```.

    For Reposeed server to run correctly the .env file is necessary.

docs:
  development: |
    Run the following commands to install reposeed-server and change your directory to reposeed's source code directory.
    ```
    go get -v -u github.com/okkur/reposeed-server
    cd $GOPATH/src/github.com/okkur/reposeed-server
    ```

    Rename .env.example to .env and change the values in the file.   
    Then run the following command to install **packr**
    ```
    make packr
    ```

    In case you made any changes on templates run ```make``` or ```packr install .``` to bundle templates into the generated binary.

emails:
  commercialSupport: "support@okkur.io"
  security: "security@okkur.io"
  coc: "coc@okkur.io"

copyright:
  owner: "The RepoSeed-server authors"
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://github.com/okkur/reposeed-server"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-beta-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/okkur/reposeed.svg"
    link: "https://github.com/okkur/reposeed/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/okkur/reposeed.svg"
    link: "LICENSE"
    alt: "license"
